In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("D:/gradproject/student-mat.csv", sep=';')

In [3]:
data = data[['G1','G2', 'G3', 'studytime', 'failures', 'absences', 'age' ]]

In [4]:
data.head()

G1  G2  G3  studytime  failures  absences  age
0   5   6   6          2         0         6   18
1   5   5   6          2         0         4   17
2   7   8  10          2         3        10   15
3  15  14  15          3         0         2   15
4   6  10  10          2         0         4   16

In [5]:
data.rename(columns= {'G1':'NOT1',
                     'G2':'NOT2',
                     'G3':'Final',
                     'studytime' : 'calisma_suresi',
                     'failures' : 'sinif_tekrari',
                     'absences' : 'Devamsizlik',
                     'age' : 'Yas'},
           inplace = True)

In [20]:
data.head(10)

NOT1  NOT2  Final  calisma_suresi  sinif_tekrari  Devamsizlik  Yas
0     5     6      6               2              0            6   18
1     5     5      6               2              0            4   17
2     7     8     10               2              3           10   15
3    15    14     15               3              0            2   15
4     6    10     10               2              0            4   16
5    15    15     15               2              0           10   16
6    12    12     11               2              0            0   16
7     6     5      6               2              0            6   17
8    16    18     19               2              0            0   15
9    14    15     15               2              0            0   15

In [7]:
data.dtypes

NOT1              int64
NOT2              int64
Final             int64
calisma_suresi    int64
sinif_tekrari     int64
Devamsizlik       int64
Yas               int64
dtype: object

In [8]:
import numpy as np
y=np.array(data['Final'])
x = np.array(data.drop('Final', axis=1))



In [9]:
from sklearn.model_selection import train_test_split

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
linear = LinearRegression()

In [13]:
linear.fit(x_train, y_train)

LinearRegression()

In [14]:
linear.score(x_test, y_test)

0.8325898318712225

In [15]:
linear.score(x_train, y_train)

0.8261275475197141

In [16]:
print('Katsayılar: \n', linear.coef_)
print('Sabit: \n', linear.intercept_)

Katsayılar: 
 [ 0.19575962  0.95558174 -0.24215827  0.12730705  0.03566925 -0.23224281]
Sabit: 
 2.154909740675155


In [24]:
data.head(30)

NOT1  NOT2  Final  calisma_suresi  sinif_tekrari  Devamsizlik  Yas
0      5     6      6               2              0            6   18
1      5     5      6               2              0            4   17
2      7     8     10               2              3           10   15
3     15    14     15               3              0            2   15
4      6    10     10               2              0            4   16
5     15    15     15               2              0           10   16
6     12    12     11               2              0            0   16
7      6     5      6               2              0            6   17
8     16    18     19               2              0            0   15
9     14    15     15               2              0            0   15
10    10     8      9               2              0            0   15
11    10    12     12               3              0            4   15
12    14    14     14               1              0            2   15
13    10    10     11               2              0            2   15
14    14    16     16               3              0            0   15
15    14    14     14               1              0            4   16
16    13    14     14               3              0            6   16
17     8    10     10               2              0            4   16
18     6     5      5               1              3           16   17
19     8    10     10               1              0            4   16
20    13    14     15               2              0            0   15
21    12    15     15               1              0            0   15
22    15    15     16               2              0            2   16
23    13    13     12               2              0            0   16
24    10     9      8               3              0            2   15
25     6     9      8               1              2           14   16
26    12    12     11               1              0            2   15
27    15    16     15               1              0            4   15
28    11    11     11               2              0            4   16
29    10    12     11               2              0           16   16

In [18]:
new_data = np.array([[10,14,3,0,4,16]])
linear.predict(new_data)

array([13.19096755])

In [19]:
new_data2 = np.array([[15,14,3,0,2,15]])
linear.predict(new_data2)

array([14.33066999])

In [22]:
new_data3 = np.array([[16,18,2,0,0,15]])
linear.predict(new_data3)

array([18.51957635])

In [23]:
new_data4 = np.array([[6,5,1,3,16,17]])
linear.predict(new_data4)

array([4.8697192])

In [26]:
new_data5 = np.array([[11,11,2,0,4,16]])
linear.predict(new_data5)

array([10.76214022])