In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("D:/gradproject/student-mat.csv", sep=';')

In [3]:
data = data[['G1','G2', 'G3', 'studytime', 'failures', 'absences', 'age' ]]

In [4]:
data.rename(columns= {'G1':'NOT1',
                     'G2':'NOT2',
                     'G3':'Final',
                     'studytime' : 'calisma_suresi',
                     'failures' : 'sinif_tekrari',
                     'absences' : 'Devamsizlik',
                     'age' : 'Yas'},
           inplace = True)

In [5]:
data.head(10)

NOT1  NOT2  Final  calisma_suresi  sinif_tekrari  Devamsizlik  Yas
0     5     6      6               2              0            6   18
1     5     5      6               2              0            4   17
2     7     8     10               2              3           10   15
3    15    14     15               3              0            2   15
4     6    10     10               2              0            4   16
5    15    15     15               2              0           10   16
6    12    12     11               2              0            0   16
7     6     5      6               2              0            6   17
8    16    18     19               2              0            0   15
9    14    15     15               2              0            0   15

In [6]:
import numpy as np
y=np.array(data['Final'])
x = np.array(data.drop('Final', axis=1))

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [10]:
from sklearn.linear_model import Ridge

In [11]:
ridge = Ridge()

In [13]:
ridge.fit(x_train,y_train)

Ridge()

In [14]:
ridge.score(x_train,y_train)

0.8261273936520598

In [15]:
ridge.score(x_test,y_test)

0.832746206135308

In [16]:
print('Katsayılar: \n', ridge.coef_)
print('Sabit: \n', ridge.intercept_)

Katsayılar: 
 [ 0.19612326  0.95500329 -0.24106519  0.12589503  0.03566486 -0.2317347 ]
Sabit: 
 2.146917457630529


In [17]:
new_data = np.array([[10,14,3,0,4,16]])
ridge.predict(new_data)

array([13.18990475])

In [19]:
new_data2 = np.array([[15,14,3,0,2,15]])
ridge.predict(new_data2)

array([14.33092603])

In [22]:
from sklearn.linear_model import Lasso

In [23]:
lasso=Lasso().fit(x_train,y_train)

In [24]:
print(lasso.score(x_train, y_train))
print(lasso.score(x_test, y_test))

0.8152685190522889
0.8413543116317268


In [25]:
import numpy as np

In [26]:
np.sum(lasso.coef_!=0)

3

In [27]:
lasso0=Lasso(alpha=0.01,max_iter=1000000).fit(x_train,y_train)
print(lasso0.score(x_train,y_train))
print(lasso0.score(x_test,y_test))

0.8261015563202313
0.8356293436494571


In [30]:
new_data2 = np.array([[15,14,3,0,2,15]])
lasso0.predict(new_data2)

array([14.32352072])

In [31]:
from sklearn.linear_model import LogisticRegression

In [32]:
logreg = LogisticRegression(solver = 'liblinear').fit(x_train, y_train)

In [33]:
print(logreg.score(x_train, y_train))
print(logreg.score(x_test, y_test))

0.39556962025316456
0.2911392405063291


In [36]:
logreg = LogisticRegression(C=0.01, solver = 'liblinear').fit(x_train, y_train)

In [37]:
print(logreg.score(x_train, y_train))
print(logreg.score(x_test, y_test))

0.33860759493670883
0.31645569620253167
